Nuevo juego
ITIC-ITESME/juego-FcoCarreto pull request #1
Opened 2021-11-09 16:23 UTC by FcoCarreto

Se agrego un nuevo juego de dados utilizando el módulo random

2021-11-11 02:15 UTC, ingrafaelcr commented
Se encuentra en verificación la funcionalidad que enviaste.

2021-11-12 00:41 UTC, FcoCarreto commented
Enterado estoy a espera , por cualquier duda.

2021-11-12 01:14 UTC, ingrafaelcr requested changes
Se verificaron las nueva función de dados, esta todo correcto. solo falta agregar datos de los juegos en el archivo README del proyecto.

2021-11-12 01:28 UTC, FcoCarreto commented
Enterado modificare el README

2021-11-12 02:06 UTC, ingrafaelcr approved these changes
Excelente se enviara a merge.

2021-11-12 02:07 UTC, merged